export const categories = [
  { id: "pizza", restaurantId: "giros-king", name: "Pizza", icon: "PZ", description: "Stone baked signatures", sortOrder: 1, visible: true },
  { id: "boxes", restaurantId: "giros-king", name: "Boxes", icon: "BX", description: "Meal boxes and bundles", sortOrder: 2, visible: true },
  { id: "pasta", restaurantId: "giros-king", name: "Pasta", icon: "PA", description: "Comfort bowls", sortOrder: 3, visible: true },
  { id: "snacks", restaurantId: "giros-king", name: "Snacks & Chicken", icon: "SC", description: "Sides and chicken", sortOrder: 4, visible: true },
  { id: "drinks", restaurantId: "giros-king", name: "Drinks", icon: "DR", description: "Cold drinks", sortOrder: 5, visible: true },
  { id: "desserts", restaurantId: "giros-king", name: "Desserts", icon: "DS", description: "Sweet finish", sortOrder: 6, visible: true },
  { id: "offers", restaurantId: "giros-king", name: "Offers", icon: "OF", description: "Deals and vouchers", sortOrder: 7, visible: true },
];

export const products = [
  {
    id: "aegean-pizza",
    restaurantId: "giros-king",
    name: "Aegean King Pizza",
    category: "pizza",
    featured: true,
    price: 12.9,
    prep: 12,
    rating: 4.9,
    image: "assets/giros-hero.png",
    icon: "AK",
    description: "Tomato sauce, mozzarella, gyros-style chicken, red onion, peppers, oregano.",
    available: true,
    bestseller: true,
    spicy: false,
    vegetarian: false,
    allergens: "Gluten, dairy",
    ingredients: "Dough, tomato sauce, mozzarella, chicken, red onion, peppers, oregano",
    sortOrder: 1,
    options: ["Small", "Medium", "Large"],
  },
  {
    id: "margherita-blue",
    restaurantId: "giros-king",
    name: "Margherita Fresh",
    category: "pizza",
    featured: true,
    price: 9.9,
    prep: 10,
    rating: 4.8,
    image: "assets/giros-hero.png",
    icon: "MF",
    description: "Tomato sauce, mozzarella, basil, olive oil.",
    available: true,
    bestseller: false,
    spicy: false,
    vegetarian: true,
    allergens: "Gluten, dairy",
    ingredients: "Dough, tomato sauce, mozzarella, basil",
    sortOrder: 2,
    options: ["Small", "Medium", "Large"],
  },
  {
    id: "spicy-salami",
    restaurantId: "giros-king",
    name: "Spicy Salami",
    category: "pizza",
    featured: true,
    price: 13.9,
    prep: 16,
    rating: 4.9,
    image: "assets/giros-hero.png",
    icon: "SS",
    description: "Tomato sauce, mozzarella, spicy salami, jalapeno, chili oil.",
    available: true,
    bestseller: true,
    spicy: true,
    vegetarian: false,
    allergens: "Gluten, dairy",
    ingredients: "Dough, tomato sauce, mozzarella, salami, jalapeno",
    sortOrder: 3,
    options: ["Small", "Medium", "Large"],
  },
  {
    id: "family-box",
    restaurantId: "giros-king",
    name: "Family Pizza Box",
    category: "boxes",
    featured: false,
    price: 29.9,
    prep: 18,
    rating: 4.7,
    image: "assets/giros-hero.png",
    icon: "FB",
    description: "Two medium pizzas, garlic dip, fries, and a large drink.",
    available: true,
    bestseller: true,
    spicy: false,
    vegetarian: false,
    allergens: "Gluten, dairy",
    ingredients: "Pizza, fries, dip, drink",
    sortOrder: 4,
    options: ["Classic bundle", "Chicken bundle", "Veggie bundle"],
  },
  {
    id: "pasta-alfredo",
    restaurantId: "giros-king",
    name: "Chicken Alfredo Pasta",
    category: "pasta",
    featured: false,
    price: 11.9,
    prep: 13,
    rating: 4.8,
    image: "assets/giros-hero.png",
    icon: "CA",
    description: "Cream sauce, chicken, parmesan, parsley.",
    available: true,
    bestseller: false,
    spicy: false,
    vegetarian: false,
    allergens: "Dairy",
    ingredients: "Pasta, cream, chicken, parmesan",
    sortOrder: 5,
    options: ["Regular", "Extra chicken", "No parsley"],
  },
  {
    id: "chicken-kickers",
    restaurantId: "giros-king",
    name: "Chicken Kickers",
    category: "snacks",
    featured: true,
    price: 7.9,
    prep: 8,
    rating: 4.8,
    image: "assets/giros-hero.png",
    icon: "CK",
    description: "Crispy chicken bites with your choice of dip.",
    available: true,
    bestseller: true,
    spicy: true,
    vegetarian: false,
    allergens: "Dairy",
    ingredients: "Chicken, crispy coating, seasoning",
    sortOrder: 6,
    options: ["Garlic dip", "BBQ dip", "Chili dip"],
  },
  {
    id: "pizza-rolls",
    restaurantId: "giros-king",
    name: "Pizza Rolls",
    category: "snacks",
    featured: false,
    price: 5.9,
    prep: 7,
    rating: 4.6,
    image: "assets/giros-hero.png",
    icon: "PR",
    description: "Warm rolls filled with cheese and tomato.",
    available: true,
    bestseller: false,
    spicy: false,
    vegetarian: true,
    allergens: "Gluten, dairy",
    ingredients: "Dough, cheese, tomato sauce",
    sortOrder: 7,
    options: ["Garlic dip", "Tomato dip"],
  },
  {
    id: "cola",
    restaurantId: "giros-king",
    name: "Cola 0.5L",
    category: "drinks",
    featured: false,
    price: 2.9,
    prep: 2,
    rating: 4.7,
    image: "assets/giros-hero.png",
    icon: "CO",
    description: "Chilled cola bottle.",
    available: true,
    bestseller: false,
    spicy: false,
    vegetarian: true,
    allergens: "None declared",
    ingredients: "Soft drink",
    sortOrder: 8,
    options: ["Cold"],
  },
  {
    id: "lava-cake",
    restaurantId: "giros-king",
    name: "Chocolate Lava Cake",
    category: "desserts",
    featured: false,
    price: 4.9,
    prep: 6,
    rating: 4.8,
    image: "assets/giros-hero.png",
    icon: "LC",
    description: "Warm chocolate cake with a soft center.",
    available: true,
    bestseller: false,
    spicy: false,
    vegetarian: true,
    allergens: "Gluten, dairy, egg",
    ingredients: "Chocolate, flour, butter, egg",
    sortOrder: 9,
    options: ["Warm"],
  },
  {
    id: "lunch-deal",
    restaurantId: "giros-king",
    name: "Lunch Deal",
    category: "offers",
    featured: true,
    price: 14.9,
    prep: 14,
    rating: 4.8,
    image: "assets/giros-hero.png",
    icon: "LD",
    description: "Medium pizza, side, and drink until 15:00.",
    available: true,
    bestseller: false,
    spicy: false,
    vegetarian: false,
    allergens: "Gluten, dairy",
    ingredients: "Pizza, side, drink",
    sortOrder: 10,
    options: ["Margherita", "Chicken", "Spicy salami"],
  },
];

export const offerBanners = [
  { id: "banner-lunch", title: "Lunch Deal", subtitle: "Medium pizza, side and drink", productId: "lunch-deal", badge: "Save today" },
  { id: "banner-family", title: "Family Box", subtitle: "Dinner for the whole table", productId: "family-box", badge: "Popular" },
  { id: "banner-dessert", title: "Sweet finish", subtitle: "Add dessert from 4.90", productId: "lava-cake", badge: "Add-on" },
];

export const upsellProducts = [
  { id: "upsell-fries", productId: "pizza-rolls", name: "Pizza rolls", price: 5.9, image: "assets/giros-hero.png" },
  { id: "upsell-dip", productId: "garlic-dip", name: "Garlic dip", price: 1.2, image: "assets/giros-hero.png" },
  { id: "upsell-drink", productId: "cola", name: "Cola 0.5L", price: 2.9, image: "assets/giros-hero.png" },
  { id: "upsell-dessert", productId: "lava-cake", name: "Chocolate lava cake", price: 4.9, image: "assets/giros-hero.png" },
];

export const extras = [
  { id: "extra-meat", name: "Extra gyros meat", price: 3.5 },
  { id: "feta", name: "Feta crumble", price: 1.25 },
  { id: "fries", name: "Side fries", price: 2.5 },
  { id: "pita", name: "Warm pita", price: 1.5 },
];

export const sauces = [
  { id: "tzatziki", name: "Tzatziki", price: 0 },
  { id: "garlic", name: "Garlic yogurt", price: 0 },
  { id: "chili", name: "Chili honey", price: 0.75 },
  { id: "lemon", name: "Lemon dill", price: 0 },
];

export const deliveryZones = [
  { id: "zone-1", name: "Central", area: "0-2 mi", fee: 2.99, eta: "22-30 min" },
  { id: "zone-2", name: "Midtown", area: "2-5 mi", fee: 4.99, eta: "30-42 min" },
  { id: "zone-3", name: "Outer ring", area: "5-8 mi", fee: 7.99, eta: "42-55 min" },
];

export const promotions = [
  { id: "welcome", code: "KING10", label: "10% off", type: "percent", value: 10, active: true },
  { id: "lunch", code: "LUNCH5", label: "$5 off lunch", type: "fixed", value: 5, active: true },
];

export const demoOrders = [
  {
    id: "GK-1248",
    restaurantId: "giros-king",
    customer: "Maria Jensen",
    phone: "(555) 014-1120",
    email: "maria@example.com",
    status: "Accepted",
    fulfillment: "Delivery",
    zone: "Central",
    total: 32.88,
    subtotal: 29.89,
    deliveryFee: 2.99,
    discount: 0,
    paymentMethod: "Card",
    address: "18 Central Ave",
    notes: "Leave at reception",
    emailLogs: [],
    items: "Classic King Gyros, Loaded Greek Fries",
    createdAt: "12:16",
  },
  {
    id: "GK-1249",
    restaurantId: "giros-king",
    customer: "Jonas Becker",
    phone: "(555) 014-7740",
    email: "jonas@example.com",
    status: "Received",
    fulfillment: "Pickup",
    zone: "Pickup counter",
    total: 18.7,
    subtotal: 18.7,
    deliveryFee: 0,
    discount: 0,
    paymentMethod: "Apple Pay",
    address: "",
    notes: "Extra napkins",
    emailLogs: [],
    items: "Lemon Chicken Gyros, Greek Lemonade",
    createdAt: "12:22",
  },
];

export const demoCustomers = [
  { id: "cus-1", name: "Maria Jensen", email: "maria@example.com", phone: "(555) 014-1120", orders: 12, spent: 268.45, points: 640 },
  { id: "cus-2", name: "Jonas Becker", email: "jonas@example.com", phone: "(555) 014-7740", orders: 4, spent: 92.2, points: 180 },
  { id: "cus-3", name: "Priya Shah", email: "priya@example.com", phone: "(555) 014-4405", orders: 9, spent: 181.35, points: 410 },
];

export const settings = {
  restaurantId: "giros-king",
  restaurantName: "Giros King",
  logoUrl: "",
  faviconUrl: "",
  address: "24 Market Street",
  mapsUrl: "https://maps.google.com",
  email: "orders@girosking.local",
  phone: "(555) 014-2040",
  currency: "USD",
  language: "en",
  timezone: "Europe/Berlin",
  taxRate: 8.25,
  serviceFee: 0,
  termsUrl: "/terms",
  privacyUrl: "/privacy",
  online: true,
  temporaryClosed: false,
  preorderEnabled: true,
  cutoffTime: "21:30",
  defaultPrepMinutes: 18,
  maxOrdersPerSlot: 12,
  autoPrint: false,
  adminEmail: "owner@girosking.com",
  browserNotifications: true,
  customerEmailNotifications: true,
  minimumOrder: 15,
  freeDeliveryThreshold: 45,
  pickupEnabled: true,
  deliveryEnabled: true,
  loyalty: { pointsPerDollar: 1, redemptionPoints: 250, rewardValue: 5 },
  hours: [
    ["Mon", "11:00", "22:00"],
    ["Tue", "11:00", "22:00"],
    ["Wed", "11:00", "22:00"],
    ["Thu", "11:00", "22:00"],
    ["Fri", "11:00", "23:00"],
    ["Sat", "12:00", "23:00"],
    ["Sun", "12:00", "21:00"],
  ],
};
