export const categories = [
  { id: "featured", restaurantId: "giros-king", name: "Featured", icon: "★", description: "Chef-picked best sellers", sortOrder: 0, visible: true },
  { id: "gyros", restaurantId: "giros-king", name: "Gyros", icon: "◐", description: "Wrapped Greek classics", sortOrder: 1, visible: true },
  { id: "plates", restaurantId: "giros-king", name: "Plates", icon: "▣", description: "Fork-and-knife meals", sortOrder: 2, visible: true },
  { id: "sides", restaurantId: "giros-king", name: "Sides", icon: "◇", description: "Fries, pastry, dips", sortOrder: 3, visible: true },
  { id: "drinks", restaurantId: "giros-king", name: "Drinks", icon: "◌", description: "Cold drinks", sortOrder: 4, visible: true },
];

export const products = [
  {
    id: "classic-gyro",
    restaurantId: "giros-king",
    name: "Classic King Gyros",
    category: "gyros",
    featured: true,
    price: 12.95,
    prep: 12,
    rating: 4.9,
    image: "assets/giros-hero.png",
    icon: "GK",
    description: "Shaved beef and lamb, tomato, onion, parsley, and tzatziki in warm pita.",
    available: true,
    bestseller: true,
    spicy: false,
    vegetarian: false,
    allergens: "Gluten, dairy",
    ingredients: "Beef and lamb, pita, tomato, onion, parsley, tzatziki",
    sortOrder: 1,
    options: ["Warm pita", "Extra toasted", "No onions"],
  },
  {
    id: "lemon-chicken",
    restaurantId: "giros-king",
    name: "Lemon Chicken Gyros",
    category: "gyros",
    featured: true,
    price: 11.95,
    prep: 10,
    rating: 4.8,
    image: "assets/giros-hero.png",
    icon: "LC",
    description: "Charred chicken, cucumber, tomato, pickled onion, and garlic sauce.",
    available: true,
    bestseller: false,
    spicy: true,
    vegetarian: false,
    allergens: "Gluten, dairy",
    ingredients: "Chicken, pita, cucumber, tomato, pickled onion, garlic sauce",
    sortOrder: 2,
    options: ["Extra chicken", "No tomato", "Spicy"],
  },
  {
    id: "royal-plate",
    restaurantId: "giros-king",
    name: "Royal Mixed Plate",
    category: "plates",
    featured: true,
    price: 18.5,
    prep: 16,
    rating: 4.9,
    image: "assets/giros-hero.png",
    icon: "RP",
    description: "Gyros meat, chicken skewers, lemon rice, salad, fries, pita, and sauces.",
    available: true,
    bestseller: true,
    spicy: false,
    vegetarian: false,
    allergens: "Gluten, dairy",
    ingredients: "Gyros meat, chicken skewers, rice, salad, fries, pita",
    sortOrder: 3,
    options: ["Rice", "Fries", "Half salad"],
  },
  {
    id: "halloumi-pita",
    restaurantId: "giros-king",
    name: "Halloumi Garden Pita",
    category: "gyros",
    featured: false,
    price: 10.95,
    prep: 9,
    rating: 4.7,
    image: "assets/giros-hero.png",
    icon: "HG",
    description: "Grilled halloumi, roasted peppers, lettuce, herbs, and lemon yogurt.",
    available: true,
    bestseller: false,
    spicy: false,
    vegetarian: true,
    allergens: "Gluten, dairy",
    ingredients: "Halloumi, pita, roasted peppers, lettuce, herbs, lemon yogurt",
    sortOrder: 4,
    options: ["Extra halloumi", "Add chili honey", "No peppers"],
  },
  {
    id: "souvlaki-bowl",
    restaurantId: "giros-king",
    name: "Souvlaki Rice Bowl",
    category: "plates",
    featured: false,
    price: 15.75,
    prep: 13,
    rating: 4.8,
    image: "assets/giros-hero.png",
    icon: "SB",
    description: "Chicken souvlaki, lemon rice, chopped salad, feta, and oregano oil.",
    available: true,
    bestseller: false,
    spicy: false,
    vegetarian: false,
    allergens: "Dairy",
    ingredients: "Chicken souvlaki, lemon rice, salad, feta, oregano oil",
    sortOrder: 5,
    options: ["Extra feta", "Add fries", "No cucumber"],
  },
  {
    id: "loaded-fries",
    restaurantId: "giros-king",
    name: "Loaded Greek Fries",
    category: "sides",
    featured: true,
    price: 7.95,
    prep: 8,
    rating: 4.8,
    image: "assets/giros-hero.png",
    icon: "LF",
    description: "Crispy fries, feta, oregano, garlic sauce, and chili honey.",
    available: true,
    bestseller: true,
    spicy: true,
    vegetarian: true,
    allergens: "Dairy",
    ingredients: "Fries, feta, oregano, garlic sauce, chili honey",
    sortOrder: 6,
    options: ["Extra feta", "No chili honey", "Add gyros meat"],
  },
  {
    id: "spanakopita",
    restaurantId: "giros-king",
    name: "Spanakopita Bites",
    category: "sides",
    featured: false,
    price: 6.75,
    prep: 7,
    rating: 4.6,
    image: "assets/giros-hero.png",
    icon: "SP",
    description: "Spinach and feta pastry bites with lemon dill dip.",
    available: true,
    bestseller: false,
    spicy: false,
    vegetarian: true,
    allergens: "Gluten, dairy",
    ingredients: "Spinach, feta, phyllo, lemon dill dip",
    sortOrder: 7,
    options: ["Extra dip", "Add chili oil"],
  },
  {
    id: "sparkling-lemonade",
    restaurantId: "giros-king",
    name: "Greek Lemonade",
    category: "drinks",
    featured: false,
    price: 4.25,
    prep: 2,
    rating: 4.7,
    image: "assets/giros-hero.png",
    icon: "GL",
    description: "Sparkling lemonade with mint and citrus syrup.",
    available: true,
    bestseller: false,
    spicy: false,
    vegetarian: true,
    allergens: "None declared",
    ingredients: "Sparkling water, lemon syrup, mint",
    sortOrder: 8,
    options: ["Less ice", "Extra mint"],
  },
];

export const extras = [
  { id: "extra-meat", name: "Extra gyros meat", price: 3.5 },
  { id: "feta", name: "Feta crumble", price: 1.25 },
  { id: "fries", name: "Side fries", price: 2.5 },
  { id: "pita", name: "Warm pita", price: 1.5 },
];

export const sauces = [
  { id: "tzatziki", name: "Tzatziki", price: 0 },
  { id: "garlic", name: "Garlic yogurt", price: 0 },
  { id: "chili", name: "Chili honey", price: 0.75 },
  { id: "lemon", name: "Lemon dill", price: 0 },
];

export const deliveryZones = [
  { id: "zone-1", name: "Central", area: "0-2 mi", fee: 2.99, eta: "22-30 min" },
  { id: "zone-2", name: "Midtown", area: "2-5 mi", fee: 4.99, eta: "30-42 min" },
  { id: "zone-3", name: "Outer ring", area: "5-8 mi", fee: 7.99, eta: "42-55 min" },
];

export const promotions = [
  { id: "welcome", code: "KING10", label: "10% off", type: "percent", value: 10, active: true },
  { id: "lunch", code: "LUNCH5", label: "$5 off lunch", type: "fixed", value: 5, active: true },
];

export const demoOrders = [
  {
    id: "GK-1248",
    restaurantId: "giros-king",
    customer: "Maria Jensen",
    phone: "(555) 014-1120",
    email: "maria@example.com",
    status: "Accepted",
    fulfillment: "Delivery",
    zone: "Central",
    total: 32.88,
    subtotal: 29.89,
    deliveryFee: 2.99,
    discount: 0,
    paymentMethod: "Card",
    address: "18 Central Ave",
    notes: "Leave at reception",
    emailLogs: [],
    items: "Classic King Gyros, Loaded Greek Fries",
    createdAt: "12:16",
  },
  {
    id: "GK-1249",
    restaurantId: "giros-king",
    customer: "Jonas Becker",
    phone: "(555) 014-7740",
    email: "jonas@example.com",
    status: "Received",
    fulfillment: "Pickup",
    zone: "Pickup counter",
    total: 18.7,
    subtotal: 18.7,
    deliveryFee: 0,
    discount: 0,
    paymentMethod: "Apple Pay",
    address: "",
    notes: "Extra napkins",
    emailLogs: [],
    items: "Lemon Chicken Gyros, Greek Lemonade",
    createdAt: "12:22",
  },
];

export const demoCustomers = [
  { id: "cus-1", name: "Maria Jensen", email: "maria@example.com", phone: "(555) 014-1120", orders: 12, spent: 268.45, points: 640 },
  { id: "cus-2", name: "Jonas Becker", email: "jonas@example.com", phone: "(555) 014-7740", orders: 4, spent: 92.2, points: 180 },
  { id: "cus-3", name: "Priya Shah", email: "priya@example.com", phone: "(555) 014-4405", orders: 9, spent: 181.35, points: 410 },
];

export const settings = {
  restaurantId: "giros-king",
  restaurantName: "Giros King",
  logoUrl: "",
  faviconUrl: "",
  address: "24 Market Street",
  mapsUrl: "https://maps.google.com",
  email: "orders@girosking.local",
  phone: "(555) 014-2040",
  currency: "USD",
  language: "en",
  timezone: "Europe/Berlin",
  taxRate: 8.25,
  serviceFee: 0,
  termsUrl: "/terms",
  privacyUrl: "/privacy",
  online: true,
  temporaryClosed: false,
  preorderEnabled: true,
  cutoffTime: "21:30",
  defaultPrepMinutes: 18,
  maxOrdersPerSlot: 12,
  autoPrint: false,
  adminEmail: "owner@girosking.com",
  browserNotifications: true,
  customerEmailNotifications: true,
  minimumOrder: 15,
  freeDeliveryThreshold: 45,
  pickupEnabled: true,
  deliveryEnabled: true,
  loyalty: { pointsPerDollar: 1, redemptionPoints: 250, rewardValue: 5 },
  hours: [
    ["Mon", "11:00", "22:00"],
    ["Tue", "11:00", "22:00"],
    ["Wed", "11:00", "22:00"],
    ["Thu", "11:00", "22:00"],
    ["Fri", "11:00", "23:00"],
    ["Sat", "12:00", "23:00"],
    ["Sun", "12:00", "21:00"],
  ],
};
